[2025-03-05T23:11:41.560+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-05T23:11:41.565+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: forecast_stock_prices.store_forecast_in_snowflake manual__2025-03-05T23:11:37.356880+00:00 [queued]>
[2025-03-05T23:11:41.567+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: forecast_stock_prices.store_forecast_in_snowflake manual__2025-03-05T23:11:37.356880+00:00 [queued]>
[2025-03-05T23:11:41.567+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-03-05T23:11:41.571+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): store_forecast_in_snowflake> on 2025-03-05 23:11:37.356880+00:00
[2025-03-05T23:11:41.575+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=793) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-05T23:11:41.575+0000] {standard_task_runner.py:72} INFO - Started process 803 to run task
[2025-03-05T23:11:41.575+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'forecast_stock_prices', 'store_forecast_in_snowflake', 'manual__2025-03-05T23:11:37.356880+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/forecast_stock_prices.py', '--cfg-path', '/tmp/tmpn7ta8d7d']
[2025-03-05T23:11:41.576+0000] {standard_task_runner.py:105} INFO - Job 38: Subtask store_forecast_in_snowflake
[2025-03-05T23:11:41.590+0000] {task_command.py:467} INFO - Running <TaskInstance: forecast_stock_prices.store_forecast_in_snowflake manual__2025-03-05T23:11:37.356880+00:00 [running]> on host 48a2c6bad219
[2025-03-05T23:11:41.618+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='forecast_stock_prices' AIRFLOW_CTX_TASK_ID='store_forecast_in_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2025-03-05T23:11:37.356880+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-05T23:11:37.356880+00:00'
[2025-03-05T23:11:41.619+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-05T23:11:41.623+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-03-05T23:11:41.623+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-6.12.5-linuxkit-aarch64-with-glibc2.36
[2025-03-05T23:11:41.624+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-03-05T23:11:41.624+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-03-05T23:11:42.097+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-03-05T23:11:43.719+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-03-05T23:11:43.719+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-05T23:11:43.723+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-05T23:11:43.723+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=forecast_stock_prices, task_id=store_forecast_in_snowflake, run_id=manual__2025-03-05T23:11:37.356880+00:00, execution_date=20250305T231137, start_date=20250305T231141, end_date=20250305T231143
[2025-03-05T23:11:43.761+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-05T23:11:43.769+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-05T23:11:43.769+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
